import { renderCircularDepsHtml } from './sections/circularDependencies'
import { renderFixRecommendationsHtml } from './sections/fixRecommendations'
import { renderHealthScoreHtml } from './sections/healthScore'
import { renderVersionConflictsHtml } from './sections/versionConflicts'
import { getEmbeddedStyles } from './templates/styles'
import type { ReportData, ReportOptions, ReportResult } from './types'
import { MONOGUARD_VERSION } from './types'

/**
 * Generate a self-contained HTML report
 * AC3: HTML Export - self-contained, embedded styles, dark mode, collapsible, print-friendly
 */
export function generateHtmlReport(data: ReportData, options: ReportOptions): ReportResult {
  const sections: string[] = []

  if (options.sections.healthScore) {
    sections.push(renderHealthScoreHtml(data.healthScore))
  }

  if (options.sections.circularDependencies) {
    sections.push(renderCircularDepsHtml(data.circularDependencies))
  }

  if (options.sections.versionConflicts) {
    sections.push(renderVersionConflictsHtml(data.versionConflicts))
  }

  if (options.sections.fixRecommendations) {
    sections.push(renderFixRecommendationsHtml(data.fixRecommendations))
  }

  const timestamp = new Date().toISOString()
  const formattedDate = new Date().toLocaleDateString('en-US', {
    year: 'numeric',
    month: 'long',
    day: 'numeric',
    hour: '2-digit',
    minute: '2-digit',
  })

  const html = `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>${escapeHtml(options.projectName)} - Dependency Analysis Report</title>
  <style>
${getEmbeddedStyles()}
  </style>
</head>
<body>
  <div class="container">
    <header class="report-header">
      <div class="logo">
        <svg width="32" height="32" viewBox="0 0 32 32" fill="currentColor">
          <circle cx="16" cy="16" r="14" stroke="currentColor" stroke-width="2" fill="none"/>
          <path d="M16 8v8l6 4" stroke="currentColor" stroke-width="2" fill="none"/>
        </svg>
        <span>MonoGuard</span>
      </div>
      <h1>Dependency Analysis Report</h1>
      <div class="report-meta">
        <span class="project-name">${escapeHtml(options.projectName)}</span>
        <span class="timestamp">Generated: ${formattedDate}</span>
      </div>
    </header>

    <main class="report-content">
      ${sections.join('\n')}
    </main>

    <footer class="report-footer">
      <p>Generated by MonoGuard v${MONOGUARD_VERSION}</p>
      <p class="timestamp-iso">${timestamp}</p>
    </footer>
  </div>

  <script>
    document.querySelectorAll('.section-header').forEach(function(header) {
      header.addEventListener('click', function() {
        var section = header.parentElement;
        section.classList.toggle('collapsed');
      });
    });
  </script>
</body>
</html>`

  const blob = new Blob([html], { type: 'text/html' })
  const dateStr = new Date().toISOString().split('T')[0]
  const filename = `${options.projectName}-analysis-report-${dateStr}.html`

  return {
    blob,
    filename,
    format: 'html',
    sizeBytes: blob.size,
  }
}

function escapeHtml(str: string): string {
  return str
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&#039;')
}
