import { renderCircularDepsMd } from './sections/circularDependencies'
import { renderFixRecommendationsMd } from './sections/fixRecommendations'
import { renderHealthScoreMd } from './sections/healthScore'
import { renderVersionConflictsMd } from './sections/versionConflicts'
import type { ReportData, ReportOptions, ReportResult } from './types'
import { MONOGUARD_VERSION } from './types'

/**
 * Generate a Markdown report (GFM-compatible)
 * AC4: Markdown Export - valid GFM, proper tables, code blocks, heading hierarchy
 */
export function generateMarkdownReport(data: ReportData, options: ReportOptions): ReportResult {
  const sections: string[] = []

  sections.push(`# ${options.projectName} - Dependency Analysis Report\n`)
  sections.push(`> Generated by MonoGuard v${MONOGUARD_VERSION}\n`)
  sections.push(`> ${new Date().toISOString()}\n`)
  sections.push('---\n')

  if (options.sections.healthScore) {
    sections.push(renderHealthScoreMd(data.healthScore))
  }

  if (options.sections.circularDependencies) {
    sections.push(renderCircularDepsMd(data.circularDependencies))
  }

  if (options.sections.versionConflicts) {
    sections.push(renderVersionConflictsMd(data.versionConflicts))
  }

  if (options.sections.fixRecommendations) {
    sections.push(renderFixRecommendationsMd(data.fixRecommendations))
  }

  if (options.includeMetadata) {
    sections.push(renderMetadataMd(data))
  }

  const markdown = sections.join('\n')
  const blob = new Blob([markdown], { type: 'text/markdown' })
  const dateStr = new Date().toISOString().split('T')[0]
  const filename = `${options.projectName}-analysis-report-${dateStr}.md`

  return {
    blob,
    filename,
    format: 'markdown',
    sizeBytes: blob.size,
  }
}

function renderMetadataMd(data: ReportData): string {
  let md = `---\n\n## Report Metadata\n\n`
  md += `| Property | Value |\n`
  md += `|----------|-------|\n`
  md += `| Project | ${data.metadata.projectName} |\n`
  md += `| Packages Analyzed | ${data.metadata.packageCount} |\n`
  md += `| Graph Nodes | ${data.metadata.nodeCount} |\n`
  md += `| Graph Edges | ${data.metadata.edgeCount} |\n`
  md += `| Analysis Duration | ${data.metadata.analysisDuration}ms |\n`
  md += `| Generated At | ${data.metadata.generatedAt} |\n`
  md += `| MonoGuard Version | ${data.metadata.monoguardVersion} |\n\n`
  return md
}
