import type { DiagnosticReport } from '../types'
import { getDiagnosticStyles } from './diagnosticStyles'

/**
 * Generate self-contained HTML for a diagnostic report
 * AC7: PDF-Ready HTML Export - self-contained, print-friendly, with TOC
 */
export function getDiagnosticHtmlTemplate(report: DiagnosticReport): string {
  const formattedDate = new Date(report.generatedAt).toLocaleDateString('en-US', {
    year: 'numeric',
    month: 'long',
    day: 'numeric',
    hour: '2-digit',
    minute: '2-digit',
  })

  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>${escapeHtml(report.projectName)} - Diagnostic Report: ${escapeHtml(report.cycleId)}</title>
  <style>
${getDiagnosticStyles()}
  </style>
</head>
<body>
  <header class="report-header">
    <h1>Diagnostic Report</h1>
    <div class="subtitle">
      ${escapeHtml(report.projectName)} &middot; Cycle: ${escapeHtml(report.cycleId)} &middot; ${formattedDate}
    </div>
  </header>

  <nav class="toc">
    <h2>Table of Contents</h2>
    <ul>
      <li><a href="#executive-summary">1. Executive Summary</a></li>
      <li><a href="#cycle-path">2. Cycle Path Visualization</a></li>
      <li><a href="#root-cause">3. Root Cause Analysis</a></li>
      <li><a href="#fix-strategies">4. Fix Strategies</a></li>
      <li><a href="#impact-assessment">5. Impact Assessment</a></li>
      <li><a href="#related-cycles">6. Related Cycles</a></li>
      <li><a href="#metadata">7. Report Metadata</a></li>
    </ul>
  </nav>

  ${renderExecutiveSummarySection(report)}
  ${renderCyclePathSection(report)}
  ${renderRootCauseSection(report)}
  ${renderFixStrategiesSection(report)}
  ${renderImpactAssessmentSection(report)}
  ${renderRelatedCyclesSection(report)}
  ${renderMetadataSection(report)}

  <footer class="report-footer">
    <p>Generated by MonoGuard v${escapeHtml(report.monoguardVersion)}</p>
    <p>${escapeHtml(report.metadata.generatedAt)} &middot; Duration: ${report.metadata.generationDurationMs}ms</p>
  </footer>
</body>
</html>`
}

function renderExecutiveSummarySection(report: DiagnosticReport): string {
  const s = report.executiveSummary
  return `
  <section class="section" id="executive-summary">
    <h2>1. Executive Summary</h2>
    <p>${escapeHtml(s.description)}</p>
    <div class="metric-grid">
      <div class="metric-card">
        <div class="metric-value"><span class="severity-badge severity-${s.severity}">${s.severity}</span></div>
        <div class="metric-label">Severity</div>
      </div>
      <div class="metric-card">
        <div class="metric-value">${s.cycleLength}</div>
        <div class="metric-label">Packages in Cycle</div>
      </div>
      <div class="metric-card">
        <div class="metric-value">${s.affectedPackagesCount}</div>
        <div class="metric-label">Total Affected</div>
      </div>
      <div class="metric-card">
        <div class="metric-value"><span class="effort-badge">${s.estimatedEffort}</span></div>
        <div class="metric-label">Estimated Effort</div>
      </div>
    </div>
    <p><strong>Recommendation:</strong> ${escapeHtml(s.recommendation)}</p>
  </section>`
}

function renderCyclePathSection(report: DiagnosticReport): string {
  const cp = report.cyclePath
  const nodesHtml = cp.nodes
    .map(
      (n) => `<tr><td><code>${escapeHtml(n.name)}</code></td><td>${escapeHtml(n.path)}</td></tr>`
    )
    .join('\n')
  const edgesHtml = cp.edges
    .map(
      (e) =>
        `<tr><td>${escapeHtml(e.from)}</td><td>${escapeHtml(e.to)}</td><td>${e.isBreakingPoint ? '<span class="severity-badge severity-critical">BREAK</span>' : ''}</td><td>${e.importStatement ? escapeHtml(e.importStatement) : '-'}</td></tr>`
    )
    .join('\n')

  return `
  <section class="section" id="cycle-path">
    <h2>2. Cycle Path Visualization</h2>
    ${cp.svgDiagram}
    <h3>Packages</h3>
    <table>
      <thead><tr><th>Name</th><th>Path</th></tr></thead>
      <tbody>${nodesHtml}</tbody>
    </table>
    <h3>Dependencies</h3>
    <table>
      <thead><tr><th>From</th><th>To</th><th>Status</th><th>Import</th></tr></thead>
      <tbody>${edgesHtml}</tbody>
    </table>
    <h3>Breaking Point</h3>
    <p><strong>${escapeHtml(cp.breakingPoint.fromPackage)}</strong> &rarr; <strong>${escapeHtml(cp.breakingPoint.toPackage)}</strong></p>
    <p>${escapeHtml(cp.breakingPoint.reason)}</p>
    <h3>ASCII Diagram</h3>
    <div class="code-block">${escapeHtml(cp.asciiDiagram)}</div>
  </section>`
}

function renderRootCauseSection(report: DiagnosticReport): string {
  const rc = report.rootCause
  const confidenceColor =
    rc.confidenceScore >= 80 ? '#16a34a' : rc.confidenceScore >= 50 ? '#d97706' : '#dc2626'

  let alternativesHtml = ''
  if (rc.alternativeCandidates.length > 0) {
    const rows = rc.alternativeCandidates
      .map(
        (c) =>
          `<tr><td><code>${escapeHtml(c.package)}</code></td><td>${escapeHtml(c.reason)}</td><td>${c.confidence}%</td></tr>`
      )
      .join('\n')
    alternativesHtml = `
      <h3>Alternative Candidates</h3>
      <table>
        <thead><tr><th>Package</th><th>Reason</th><th>Confidence</th></tr></thead>
        <tbody>${rows}</tbody>
      </table>`
  }

  let refsHtml = ''
  if (rc.codeReferences.length > 0) {
    const rows = rc.codeReferences
      .map(
        (r) =>
          `<tr><td><code>${escapeHtml(r.file)}:${r.line}</code></td><td><code>${escapeHtml(r.importStatement)}</code></td></tr>`
      )
      .join('\n')
    refsHtml = `
      <h3>Code References</h3>
      <table>
        <thead><tr><th>Location</th><th>Import</th></tr></thead>
        <tbody>${rows}</tbody>
      </table>`
  }

  return `
  <section class="section" id="root-cause">
    <h2>3. Root Cause Analysis</h2>
    <p>${escapeHtml(rc.explanation)}</p>
    <div class="metric-grid">
      <div class="metric-card">
        <div class="metric-value" style="color: ${confidenceColor}">${rc.confidenceScore}%</div>
        <div class="metric-label">Confidence</div>
      </div>
      <div class="metric-card">
        <div class="metric-value"><code>${escapeHtml(rc.originatingPackage)}</code></div>
        <div class="metric-label">Originating Package</div>
      </div>
    </div>
    <p><strong>Reason:</strong> ${escapeHtml(rc.originatingReason)}</p>
    ${alternativesHtml}
    ${refsHtml}
  </section>`
}

function renderFixStrategiesSection(report: DiagnosticReport): string {
  if (report.fixStrategies.length === 0) {
    return `
    <section class="section" id="fix-strategies">
      <h2>4. Fix Strategies</h2>
      <p>No fix strategies available for this cycle.</p>
    </section>`
  }

  const strategiesHtml = report.fixStrategies
    .map((fs) => {
      const stepsHtml =
        fs.steps.length > 0
          ? `<ol class="step-list">${fs.steps.map((s) => `<li><strong>${escapeHtml(s.title)}</strong><br/>${escapeHtml(s.description)}${s.codeSnippet ? `<div class="code-block">${escapeHtml(s.codeSnippet)}</div>` : ''}</li>`).join('\n')}</ol>`
          : ''

      const codeHtml =
        fs.codeSnippets.before || fs.codeSnippets.after
          ? `<h4>Code Changes</h4>
           ${fs.codeSnippets.before ? `<p><strong>Before:</strong></p><div class="code-block">${escapeHtml(fs.codeSnippets.before)}</div>` : ''}
           ${fs.codeSnippets.after ? `<p><strong>After:</strong></p><div class="code-block">${escapeHtml(fs.codeSnippets.after)}</div>` : ''}`
          : ''

      return `
      <div class="strategy-card">
        <h3>${escapeHtml(fs.title)} <span class="effort-badge">${fs.estimatedEffort}</span></h3>
        <p>${escapeHtml(fs.description)}</p>
        <p>Suitability: <strong>${fs.suitabilityScore}/10</strong> &middot; Estimated: ${escapeHtml(fs.estimatedTime)}</p>
        <div class="pros-cons">
          <div>
            <strong>Pros</strong>
            <ul class="pros">${fs.pros.map((p) => `<li>${escapeHtml(p)}</li>`).join('')}</ul>
          </div>
          <div>
            <strong>Cons</strong>
            <ul class="cons">${fs.cons.map((c) => `<li>${escapeHtml(c)}</li>`).join('')}</ul>
          </div>
        </div>
        ${stepsHtml}
        ${codeHtml}
      </div>`
    })
    .join('\n')

  return `
  <section class="section" id="fix-strategies">
    <h2>4. Fix Strategies</h2>
    ${strategiesHtml}
  </section>`
}

function renderImpactAssessmentSection(report: DiagnosticReport): string {
  const ia = report.impactAssessment
  return `
  <section class="section" id="impact-assessment">
    <h2>5. Impact Assessment</h2>
    <div class="metric-grid">
      <div class="metric-card">
        <div class="metric-value">${ia.directParticipantsCount}</div>
        <div class="metric-label">Direct Participants</div>
      </div>
      <div class="metric-card">
        <div class="metric-value">${ia.indirectDependentsCount}</div>
        <div class="metric-label">Indirect Dependents</div>
      </div>
      <div class="metric-card">
        <div class="metric-value">${ia.totalAffectedCount}</div>
        <div class="metric-label">Total Affected</div>
      </div>
      <div class="metric-card">
        <div class="metric-value">${ia.percentageOfMonorepo}%</div>
        <div class="metric-label">Of Monorepo</div>
      </div>
    </div>
    <p><span class="severity-badge severity-${ia.riskLevel}">${ia.riskLevel} risk</span></p>
    <p>${escapeHtml(ia.riskExplanation)}</p>
    <h3>Direct Participants</h3>
    <ul>${ia.directParticipants.map((p) => `<li><code>${escapeHtml(p)}</code></li>`).join('')}</ul>
    ${ia.indirectDependents.length > 0 ? `<h3>Indirect Dependents</h3><ul>${ia.indirectDependents.map((p) => `<li><code>${escapeHtml(p)}</code></li>`).join('')}</ul>` : ''}
  </section>`
}

function renderRelatedCyclesSection(report: DiagnosticReport): string {
  if (report.relatedCycles.length === 0) {
    return `
    <section class="section" id="related-cycles">
      <h2>6. Related Cycles</h2>
      <p>No related cycles detected.</p>
    </section>`
  }

  const rows = report.relatedCycles
    .map(
      (rc) =>
        `<tr>
          <td>${escapeHtml(rc.cycleId)}</td>
          <td>${rc.sharedPackages.map((p) => `<code>${escapeHtml(p)}</code>`).join(', ')}</td>
          <td>${rc.overlapPercentage}%</td>
          <td>${rc.recommendFixTogether ? '✅ Yes' : 'No'}</td>
          <td>${rc.reason ? escapeHtml(rc.reason) : '-'}</td>
        </tr>`
    )
    .join('\n')

  return `
  <section class="section" id="related-cycles">
    <h2>6. Related Cycles</h2>
    <table>
      <thead><tr><th>Cycle</th><th>Shared Packages</th><th>Overlap</th><th>Fix Together?</th><th>Reason</th></tr></thead>
      <tbody>${rows}</tbody>
    </table>
  </section>`
}

function renderMetadataSection(report: DiagnosticReport): string {
  const m = report.metadata
  return `
  <section class="section" id="metadata">
    <h2>7. Report Metadata</h2>
    <table>
      <tbody>
        <tr><td><strong>Generated At</strong></td><td>${escapeHtml(m.generatedAt)}</td></tr>
        <tr><td><strong>Generation Time</strong></td><td>${m.generationDurationMs}ms</td></tr>
        <tr><td><strong>MonoGuard Version</strong></td><td>${escapeHtml(m.monoguardVersion)}</td></tr>
        <tr><td><strong>Project</strong></td><td>${escapeHtml(m.projectName)}</td></tr>
        <tr><td><strong>Cycle ID</strong></td><td>${escapeHtml(report.cycleId)}</td></tr>
        <tr><td><strong>Report ID</strong></td><td>${escapeHtml(report.id)}</td></tr>
      </tbody>
    </table>
  </section>`
}

function escapeHtml(str: string): string {
  return str
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&#039;')
}
