#!/bin/bash

# MonoGuard Zeabur Setup Script
# This script helps prepare the project for Zeabur deployment

set -e

echo "🚀 MonoGuard Zeabur Setup Script"
echo "================================="

# Check if zeabur.yaml exists
if [ ! -f "zeabur.yaml" ]; then
    echo "❌ zeabur.yaml not found in project root"
    exit 1
fi

echo "✅ Found zeabur.yaml configuration"

# Check if .env.example exists
if [ ! -f ".env.example" ]; then
    echo "❌ .env.example not found in project root"
    exit 1
fi

echo "✅ Found .env.example template"

# Create .env file if it doesn't exist
if [ ! -f ".env" ]; then
    echo "📝 Creating .env file from template..."
    cp .env.example .env
    echo "✅ Created .env file (please configure your values)"
else
    echo "✅ .env file already exists"
fi

# Check if Dockerfiles exist
echo "🐳 Checking Dockerfiles..."

if [ -f "apps/api/Dockerfile" ]; then
    echo "✅ API Dockerfile found"
else
    echo "❌ API Dockerfile missing at apps/api/Dockerfile"
fi

if [ -f "apps/frontend/Dockerfile" ]; then
    echo "✅ Frontend Dockerfile found"
else
    echo "❌ Frontend Dockerfile missing at apps/frontend/Dockerfile"
fi

# Check if package files exist
echo "📦 Checking package files..."

if [ -f "apps/api/go.mod" ]; then
    echo "✅ Go modules found (apps/api/go.mod)"
else
    echo "❌ Go modules missing at apps/api/go.mod"
fi

if [ -f "apps/frontend/package.json" ]; then
    echo "✅ Frontend package.json found"
else
    echo "❌ Frontend package.json missing at apps/frontend/package.json"
fi

if [ -f "apps/cli/package.json" ]; then
    echo "✅ CLI package.json found"
else
    echo "❌ CLI package.json missing at apps/cli/package.json"
fi

# Generate secure secrets for environment variables
echo "🔐 Generating secure secrets..."

# Generate JWT secret
JWT_SECRET=$(openssl rand -hex 32)
NEXTAUTH_SECRET=$(openssl rand -hex 32)

echo ""
echo "🔑 Generated secrets (add these to your Zeabur environment variables):"
echo "JWT_SECRET=$JWT_SECRET"
echo "NEXTAUTH_SECRET=$NEXTAUTH_SECRET"
echo ""

# Check if GitHub OAuth is configured
echo "🔍 Checking GitHub OAuth configuration..."
echo "Don't forget to:"
echo "1. Create GitHub OAuth App at https://github.com/settings/developers"
echo "2. Set Homepage URL: https://your-app.zeabur.app"  
echo "3. Set Authorization callback URL: https://your-app.zeabur.app/api/auth/callback/github"
echo "4. Add GITHUB_CLIENT_ID and GITHUB_CLIENT_SECRET to Zeabur environment variables"
echo ""

# Display next steps
echo "📋 Next Steps for Zeabur Deployment:"
echo "1. Push your code to GitHub repository"
echo "2. Connect repository to Zeabur (https://zeabur.com)"
echo "3. Add environment variables in Zeabur dashboard:"
echo "   - JWT_SECRET (generated above)"
echo "   - NEXTAUTH_SECRET (generated above)"
echo "   - GITHUB_CLIENT_ID (from GitHub OAuth app)"
echo "   - GITHUB_CLIENT_SECRET (from GitHub OAuth app)"
echo "   - POSTGRES_PASSWORD (auto-generated by Zeabur)"
echo "   - REDIS_PASSWORD (auto-generated by Zeabur)"
echo "4. Deploy services in order: postgres → redis → api → frontend"
echo "5. Configure custom domain (optional)"
echo ""

echo "📚 For detailed instructions, see docs/ZEABUR_DEPLOYMENT.md"
echo "✨ Setup complete! Ready for Zeabur deployment."